sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FY2RNnz4oo9nhI6kYW/k7IEXeXAYVN6w3SleR2rJrbfHyaFQ3pLMx2yP76sDZXEnxPfR/i4DYQExTi1Z16rtj7nW9V83Jx/QrKmzBOtLuMmHpASotGSUBeRGPMJYCXZJMl8dxHtURki6OQFlKR0dFWdY6LR1mBk5WdPow7xLMp0Ln7Pmyo6ignFK3EPFlvTdYTnoDJG2TITutY4HBIa2UR1dNDR3mvYX3gf3QHDwj58MjWC7pWQXWYFNrb+LS/z8WPOZazXOOuNIJf6AMIv8N7w6tC9Xv30UB1izUB04v2yLyMJ2tOpST+LtFWJetWsVH3Itzu3kqM65kbccYUDGwiZyAzWWBZ7VicFJ9jF0bFM8dEjGMbDI2j8A4TdwIGNaitpHhHiy8ntCDbxPKTZFC16iOEKEsSRg1bypeQ48KF2ByVb2Js1A7XE53Y7kkJ4zna7srBxYsrsjj4dqLuzK9UX2Ut9kkI7SG5PPTtEmfgKYj5QS4qSD0o/w0PeEJTx9uZ43LyNiPmWFbRvbDYldNJA+u9Drg7IqRuNKUFKnSgGZKwM6y+uRWXcinqM0q5j+g6T3UFmk4oyvKX/gwDJ2mRf0nHxgOLmbUgZ2WkMGmn+ICG1iQgmmzXM2GUMnwgUoAjD6f3607qvwlqMvvtZwQ6FHF5yISLXsuSG9SsB+QWQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/History-of-the-Decline-and-Fall-of-the-Roman-Empire---Volume-3_733
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy